// Generated by CoffeeScript 1.8.0
FB.init({
  appId: '652484128121792',
  status: true,
  cookie: true,
  xfbml: true,
  version: 'v2.1'
});

FB.login(function() {
  console.log('FB.getAccessToken() ->', FB.getAccessToken());
  FB.api('/me', function(me) {
    return console.log('/me ->', me);
  });
  return FB.api('/v1.0/me', function(me) {
    return console.log('/v1.0/me ->', me);
  });
});
