// Generated by CoffeeScript 1.8.0
FB.init({
  appId: '652484128121792',
  status: true,
  cookie: true,
  xfbml: true,
  version: 'v2.1'
});

FB.login(function() {
  var fbToken;
  if (!FB.getAccessToken()) {
    console.log('FB login failed');
  }
  fbToken = FB.getAccessToken();
  return FB.api('/me', function(me) {
    return console.log(me);
  });
});
